# Generated by Django 6.0 on 2025-12-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_post_options_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="body",
            field=models.TextField(max_length=400, null=True),
        ),
    ]
